### ISSUE TITLE
Task 2 (Mockup)

### ISSUE THREAD

**Issue by ala-n** [TwoCoR/Senkovsky7#2]
[-] No comments at all, so behaviours are unclear.
   Mockup should show the basic concept of application design and get ability to understand the TP.
[-] example: footer is not shown,  again whole TP should be carefully covered 
[-] just an arrow to some part without context, comment - is not enough at all. 
About the "my message" (menu or field, so you see I cant say definitely what was that ) even I, as a technical person, can't say almost nothing.

SO as the result :
please carefully read the task and try, another words, visualize Technical Project (https://docs.google.com/viewer?a=v&pid=sites&srcid=ZGVmYXVsdGRvbWFpbnxmYW1jc2JzdXxneDoxMDFhZTliOWIyZjU4ZmVl)

The goal of wireframes is describe TP and basically show how it will look like.
two basic screens and ton of arrows is not enough.

**Comment by TwoCoR** [comment]
So should i redo Task 2?

**Comment by TwoCoR** [comment]
reworked mockup is in my repository
tell me if i missed something again
